GET http://localhost:3020/services


### bn0appointmentController.boappointmentController.bookAppointment.okAppointment.
GET http://localhost:6000/products


###
POST http://localhost:3020/appointments/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjMzNjNiNWQzMjY0YmE5YjM5Mjg1ZTAiLCJpYXQiOjE3MTQ2NDQzMDcsImV4cCI6MTcxNDkyNTEwN30.drbD2rl-Tjai8huRtiRfFD2FepqxJTryHodbmlTsWKY"
Content-Type: application/json

{
    "service": "manicure",
    "startTime": "2024-05-15T14:00:00.000Z",
    "user": "663363b5d3264ba9b39285e0"
}
###
DELETE http://localhost:3020/appointments/deleteall

###

GET http://localhost:3020/appointments/662f73e0c38ca2635c578df9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjMwZGMzODA4MTBlZGUwMzg1MGE5MDAiLCJpYXQiOjE3MTQ0NzgxNjMsImV4cCI6MTcxNDUyMTM2M30.pJP45GjcOkjpvv2bFpWWPrpM-unp7B2Np9ZW8LFL12I
###
GET http://localhost:3020/auth/users

###

POST http://localhost:3020/auth/register
Content-Type: application/json


{  
     "firstname":"hetal",
    "lastname" :"ahir",
    "email":"hetal@gmail.com",
    "password":"Vritti@143",
    "confirmPassword":"Vritti@143"
    }


###

POST http://localhost:3020/auth/login
Content-Type: application/json


{
    "email":"hetal@gmail.com",
    "password":"Vritti@143"
}

###

DELETE  http://localhost:3020/auth/users

###
Get http://localhost:3020/services
###
Get http://localhost:3020/products/


###
 POST http://localhost:3020/carts/add-to-cart/661e4349d31012d4555d7be8
Content-Type: application/json

 {
  "userId": "661e4349d31012d4555d7bea"
}


###
Get http://localhost:3020/carts/661e4349d31012d4555d7bea

# ###
# POST http://localhost:3020/send-email
# Content-Type: application/json

#  {
#   "firstName":"hetal" ,
#   "lastName":"ahir",
#    "email":"hetal@gmail.com",
#     "message":"hello"
# }
