GET http://localhost:3020/services


### bn0appointmentController.boappointmentController.bookAppointment.okAppointment.
GET http://localhost:6000/products


###
POST http://localhost:3020/appointments/book
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjQ0Zjc4MDA5NmRjNDJiMjVlODZiMjAiLCJpYXQiOjE3MTU3OTU4NTUsImV4cCI6MTcxNjA3NjY1NX0.CT71RHYtuYpfN39TnHJqURXR35YP__B_YI71rZWdUo0"
Content-Type: application/json

{
    "service": "manicure",
    "startTime": "2024-05-15T14:00:00.000Z",
    "user": "6644f780096dc42b25e86b20"
}
###
DELETE http://localhost:3020/appointments/deleteall

###

GET http://localhost:3020/appointments/662f73e0c38ca2635c578df9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjMwZGMzODA4MTBlZGUwMzg1MGE5MDAiLCJpYXQiOjE3MTQ0NzgxNjMsImV4cCI6MTcxNDUyMTM2M30.pJP45GjcOkjpvv2bFpWWPrpM-unp7B2Np9ZW8LFL12I
###
GET http://localhost:3020/auth/users

###
POST  http://localhost:3020/bookingConfirm/book
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjQxYmM0OGYyZDY0MzIxZGMwYTJmN2QiLCJpYXQiOjE3MTU2ODk5NzgsImV4cCI6MTcxNTk3MDc3OH0.n0iIH84_nkge-LheOudX8Z1277rhYGzIxmgUd2bKerM
Content-Type: application/json

{
  "bookedServices":[{
  "service": "manicure",
  "startTime": "2024-05-24T11:00:00.000Z",
  "price": 90,
  "user": "6641bc48f2d64321dc0a2f7d"
}
]
}
###
GET http://localhost:3020/bookingConfirm/6641bc48f2d64321dc0a2f7d
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjQxYmM0OGYyZDY0MzIxZGMwYTJmN2QiLCJpYXQiOjE3MTU2ODk5NzgsImV4cCI6MTcxNTk3MDc3OH0.n0iIH84_nkge-LheOudX8Z1277rhYGzIxmgUd2bKerM





###
POST http://localhost:3020/auth/register
Content-Type: application/json


{  
     "firstname":"hetal",
    "lastname" :"ahir",
    "email":"ahirhetal2409@gmail.com",
    "password":"Vrittivaniya@7",
    "confirmPassword":"Vrittivaniya@7"
    }

  
###
POST http://localhost:3020/auth/login
Content-Type: application/json


{
    "email":"ahirhetal2409@gmail.com",
    "password":"Vritti123!"
}

###

DELETE  http://localhost:3020/auth/users

###
Get http://localhost:3020/services
###
Get http://localhost:3020/products/


###
 POST http://localhost:3020/carts/add-to-cart/661e4349d31012d4555d7be8
Content-Type: application/json

 {
  "userId": "661e4349d31012d4555d7bea"
}


###
Get http://localhost:3020/carts/661e4349d31012d4555d7bea


 POST http://localhost:3020/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjNiM2JmOGU3YjdhYzVjZDk1OTRkMzgiLCJpYXQiOjE3MTUxNjI1MTUsImV4cCI6MTcxNTQ0MzMxNX0.FIO1APcvvuYYWkL_dYERq4YTF-GQeMbfLi05IGB-qTw

 {
  "products": [
    {
        "product":"663b5cc84adbafc29d0a250d",
        "quantity":1
    }
  ],
  "totalAmount":100,
  "shippingAddress": {
    "fullName": "John Doe",
    "address": "123 Apple St",
    "city": "New York",
    "state": "NY",
    "postcode": "10001",
    "country": "USA"
  }
}

###
 GET http://localhost:3020/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NjNiM2JmOGU3YjdhYzVjZDk1OTRkMzgiLCJpYXQiOjE3MTUxNjI1MTUsImV4cCI6MTcxNTQ0MzMxNX0.FIO1APcvvuYYWkL_dYERq4YTF-GQeMbfLi05IGB-qTw


###

POST http://localhost:3020/auth/forgot-password
Content-Type: application/json

 {
  "email":"ahirhetal2409@gmail.com"
}

###

POST http://localhost:3020/auth/reset-password/040ae94bf9026907dbf1773bd53ed2a9b7eadc51
Content-Type: application/json

{
   "newPassword":"Vritti123!",
   "confirmPassword":"Vritti123!"
}




